// Admin panel matching color scheme - Professional slate-based design
export const colors = {
  light: {
    background: '#ffffff',
    foreground: '#0f172a',
    card: '#ffffff',
    cardForeground: '#0f172a',
    popover: '#ffffff',
    popoverForeground: '#0f172a',
    primary: '#1e293b',
    primaryForeground: '#f8fafc',
    secondary: '#f1f5f9',
    secondaryForeground: '#1e293b',
    muted: '#f1f5f9',
    mutedForeground: '#64748b',
    accent: '#3b82f6',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#e2e8f0',
    input: '#e2e8f0',
    ring: '#1e293b',
    success: '#22c55e',
    successForeground: '#ffffff',
    warning: '#f59e0b',
    warningForeground: '#ffffff',
    info: '#3b82f6',
    infoForeground: '#ffffff',
  },
  dark: {
    background: '#0f172a',
    foreground: '#f8fafc',
    card: '#1e293b',
    cardForeground: '#f8fafc',
    popover: '#1e293b',
    popoverForeground: '#f8fafc',
    primary: '#f8fafc',
    primaryForeground: '#1e293b',
    secondary: '#334155',
    secondaryForeground: '#f8fafc',
    muted: '#334155',
    mutedForeground: '#94a3b8',
    accent: '#60a5fa',
    accentForeground: '#0f172a',
    destructive: '#dc2626',
    destructiveForeground: '#f8fafc',
    border: '#334155',
    input: '#334155',
    ring: '#cbd5e1',
    success: '#22c55e',
    successForeground: '#ffffff',
    warning: '#f59e0b',
    warningForeground: '#ffffff',
    info: '#60a5fa',
    infoForeground: '#0f172a',
  },
};

// Primary color shades (slate)
export const primary = {
  50: '#f8fafc',
  100: '#f1f5f9',
  200: '#e2e8f0',
  300: '#cbd5e1',
  400: '#94a3b8',
  500: '#64748b',
  600: '#475569',
  700: '#334155',
  800: '#1e293b',
  900: '#0f172a',
  950: '#020817',
};

export const getColors = (isDark: boolean) => isDark ? colors.dark : colors.light;

// Legacy export for backwards compatibility with old files
// These map to the light theme colors
export const Colors = {
  primary: colors.light.primary,
  background: colors.light.background,
  backgroundMuted: colors.light.muted,
  text: colors.light.foreground,
  textLight: colors.light.mutedForeground,
  error: colors.light.destructive,
  success: colors.light.success,
  warning: colors.light.warning,
  border: colors.light.border,
  card: colors.light.card,
  muted: colors.light.muted,
};
